In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from os import mkdir
from os.path import isdir

In [20]:
annotation_df = pd.read_csv("../data/annotation_KO_GO.csv")

In [21]:
for entry in annotation_df.ID:
    if type(entry) != str:
        print(entry)

nan
nan
nan

In [22]:
annotation_df["ID"] = annotation_df.ID.apply(lambda x: x.split(".")[1].replace("T","G") if type(x) == str else x)

In [23]:
annotation_df = annotation_df.drop_duplicates(keep="first")

In [24]:
annotation_df

,ID,KO,KO_definition,Score,Second.best,Score2,UniProtKB,KEGG.ID,KO.Number,GO.terms
0,G000001,NaN,NaN,6.0,K21595,1.0,NaN,NaN,NaN,NaN
1,G000002,K07188,"LIPE, HSL; hormone-sensitive lipase [EC:3.1.1.79]",171.0,NaN,NaN,P54310,LIPS_MOUSE,mmu:16890;,caveola [GO:0005901]; cytoplasm [GO:0005737]; ...
2,G000003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,G000004,NaN,NaN,8.0,K10251,1.0,NaN,NaN,NaN,NaN
4,G000004,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
37782,G028913,NaN,NaN,52.0,NaN,NaN,NaN,NaN,NaN,NaN
37783,G028914,NaN,NaN,2.0,K01883,1.0,NaN,NaN,NaN,NaN
37784,G028915,NaN,NaN,3.0,K17604,1.0,NaN,NaN,NaN,NaN
37785,G028916,NaN,NaN,9.0,K11274,1.0,P10273,POL_FLV,vg:1724726;,host cell late endosome membrane [GO:0044185];...
37786,G028917,NaN,NaN,2.0,K05625,1.0,NaN,NaN,NaN,NaN

In [25]:
unique_celltypes = pd.read_table("../results/processedData/normalized_mean/unique_celltypes.table", sep=";")

In [26]:
unique_celltypes["ID"] = unique_celltypes.ID.apply(lambda x: x.split("-")[1] if type(x) == str else x)

In [27]:
unique_celltypes

,ID,Ec_Head,En_Head,Ec_BodyCol.SC,I_ISC,Ec_Peduncle,Ec_Tentacle,I_FemGC,Ec_BasalDisk,I_Neuro,...,C_gland_cell,C_progenitor,C_neuroprogenitor,C_EC_foot,C_EN_foot,C_tentacle,C_head,L_ENDODERM,L_ECTODERM,L_INTERSTITIAL
7351,G011796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,1.0,NaN
7349,G011792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
5039,G008093,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
2037,G003526,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN
5615,G009037,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13175,G021056,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11931,G019166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
6861,G011126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
63,G000101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
4406,G007009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN

In [28]:
merged_df = annotation_df.merge(unique_celltypes, how='inner', on='ID')[annotation_df.columns]
merged_df.head()

,ID,KO,KO_definition,Score,Second.best,Score2,UniProtKB,KEGG.ID,KO.Number,GO.terms
0,G000002,K07188,"LIPE, HSL; hormone-sensitive lipase [EC:3.1.1.79]",171.0,NaN,NaN,P54310,LIPS_MOUSE,mmu:16890;,caveola [GO:0005901]; cytoplasm [GO:0005737]; ...
1,G000009,K07188,"LIPE, HSL; hormone-sensitive lipase [EC:3.1.1.79]",143.0,NaN,NaN,NaN,NaN,NaN,NaN
2,G000009,K07188,"LIPE, HSL; hormone-sensitive lipase [EC:3.1.1.79]",188.0,NaN,NaN,P54310,LIPS_MOUSE,mmu:16890;,caveola [GO:0005901]; cytoplasm [GO:0005737]; ...
3,G000010,NaN,NaN,NaN,NaN,NaN,O42342,SOX7_XENLA,xla:378665;,nucleus [GO:0005634]; sequence-specific DNA bi...
4,G000011,NaN,NaN,28.0,K07418,1.0,NaN,NaN,NaN,NaN

In [29]:
cleaned_merged_df = merged_df[["ID","KO"]].dropna()
cleaned_merged_df = cleaned_merged_df.drop_duplicates()
cleaned_merged_df.to_csv("../results/gene_enrichment/gene_to_KO.csv")

In [30]:
unique_celltypes = pd.read_table("../results/processedData/normalized_mean/unique_celltypes.table", sep=";")
unique_celltypes = unique_celltypes.fillna(0) 

ecokd1 = pd.read_csv("../results/deseq2_rsem/tables/EcoKD1_Eco1KD_B8_vs_control_B8_results.csv", header=0, index_col=0)
wild = pd.read_csv("../results/deseq2_rsem/tables/HydraRecolonization_Wild_vs_GF_results.csv", header=0, index_col=0)
cvbct = pd.read_csv("../results/deseq2_rsem/tables/HydraRecolonization_Cvbct_vs_GF_results.csv",header=0, index_col=0)
temp = pd.read_csv("../results/deseq2_rsem/tables/HydraTemperature_08°C_vs_18°C_results.csv",header=0, index_col=0)

In [14]:
# returns a dataframe with log2foldchanges for the relevant celltype and transcriptome experiment
def get_unique_genes_diffexpression_table(transcriptome_df:pd.DataFrame,celltype_df:pd.DataFrame,celltype:str)->pd.DataFrame:
    try:
        unique_genes = list(celltype_df[celltype_df[celltype] == 1].ID.apply(lambda x: x.split("-")[1]))
        transcriptome_df['gene_id'] = transcriptome_df.index
        transcriptome_df['gene_id'] = transcriptome_df['gene_id'].apply(lambda x: x.split(".")[1])
        #transcriptome_df = transcriptome_df[transcriptome_df["padj"] <= 0.05]
        #transcriptome_df = transcriptome_df[abs(transcriptome_df["log2FoldChange"]) >= 1]
        return transcriptome_df[transcriptome_df['gene_id'].isin(unique_genes)]
    except Exception as e:
        raise Exception("[-] ERROR with exception: {}".format(e))
        

def extract_celltype_genes(in_celltypes:pd.DataFrame,experiment_dataframe:pd.DataFrame,celltype:str)->pd.DataFrame:
    celltypes = in_celltypes.copy()
    cleaned_celltypes = celltypes[celltypes[celltype].isna() == False][["ID",celltype]]
    experiment_dataframe_copy = experiment_dataframe.copy()
    experiment_dataframe_copy["ID"] = experiment_dataframe.index
    experiment_dataframe_copy["ID"] = experiment_dataframe_copy.ID.apply(lambda x: "HVAEP1-" + x.split(".")[1])
    #experiment_dataframe_copy = experiment_dataframe_copy[experiment_dataframe_copy['padj'] <= 0.05]
    #experiment_dataframe_copy = experiment_dataframe_copy[abs(experiment_dataframe_copy['log2FoldChange']) >= 1]
    
    experiment_celltype = pd.merge(experiment_dataframe_copy, cleaned_celltypes, on="ID")[["ID","log2FoldChange","pvalue",celltype]]
    experiment_celltype = experiment_celltype[experiment_celltype[celltype] != 0]

    print(len(experiment_celltype), celltype)
    return experiment_celltype

In [15]:
def produce_tables_for_all_celtypes(dataframe:pd.DataFrame,
                                    celltypes:pd.DataFrame,
                                    id_to_ko_dataframe:pd.DataFrame,experiment:str):
    try:
        print("[*] working on {}".format(experiment))
        for celltype in unique_celltypes.columns:
            if celltype != "ID":
                print("[*] working with: {}".format(celltype))
                celltype_dataframe = get_unique_genes_diffexpression_table(dataframe, unique_celltypes, celltype)
                celltype_dataframe["ID"] = list(celltype_dataframe.index)
                celltype_dataframe["ID"] = celltype_dataframe.ID.apply(lambda x: x.split(".")[1])
                celltype_dataframe = id_to_ko_dataframe.merge(celltype_dataframe, on="ID")
                print("\t[*] Number of Diff. Genes: {}".format(len(celltype_dataframe)))
                if isdir("../results/gene_enrichment/" + experiment + "/") == False:
                    mkdir("../results/gene_enrichment/" + experiment + "/")
                    
                savep = "../results/gene_enrichment/" + experiment + "/" + experiment + "_" + celltype + ".csv"
                
                celltype_dataframe[["ID","KO"]].to_csv(savep)
        print("[+] DONE")
        return 0
    except Exception as e:
        raise Exception(" [-] ERROR with exception: {}".format(e))

In [31]:
produce_tables_for_all_celtypes(ecokd1, unique_celltypes, cleaned_merged_df, "ecokd1")

[*] working on ecokd1
[*] working with: Ec_Head
	[*] Number of Diff. Genes: 6
[*] working with: En_Head
	[*] Number of Diff. Genes: 4
[*] working with: Ec_BodyCol.SC
	[*] Number of Diff. Genes: 1
[*] working with: I_ISC
	[*] Number of Diff. Genes: 0
[*] working with: Ec_Peduncle
	[*] Number of Diff. Genes: 4
[*] working with: Ec_Tentacle
	[*] Number of Diff. Genes: 4
[*] working with: I_FemGC
	[*] Number of Diff. Genes: 18
[*] working with: Ec_BasalDisk
	[*] Number of Diff. Genes: 10
[*] working with: I_Neuro
	[*] Number of Diff. Genes: 0
[*] working with: I_EarlyNem
	[*] Number of Diff. Genes: 0
[*] working with: I_MaleGC
	[*] Number of Diff. Genes: 12
[*] working with: I_En2N
	[*] Number of Diff. Genes: 2
[*] working with: En_Foot
	[*] Number of Diff. Genes: 3
[*] working with: En_BodyCol.SC
	[*] Number of Diff. Genes: 0
[*] working with: I_ZymoGl
	[*] Number of Diff. Genes: 13
[*] working with: I_GlProgen
	[*] Number of Diff. Genes: 1
[*] working with: I_StenoNB
	[*] Number of Diff. Genes: 6
[*] working with: I_DesmoNC

/blast/miniconda3/lib/python3.8/site-packages/pandas/core/frame.py:3607: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)

	[*] Number of Diff. Genes: 8
[*] working with: I_IsoNC
	[*] Number of Diff. Genes: 6
[*] working with: I_StenoNC
	[*] Number of Diff. Genes: 7
[*] working with: En_Tentacle
	[*] Number of Diff. Genes: 4
[*] working with: I_Ec1N
	[*] Number of Diff. Genes: 2
[*] working with: I_Ec4N
	[*] Number of Diff. Genes: 2
[*] working with: I_SpumMucGl
	[*] Number of Diff. Genes: 7
[*] working with: I_Ec3N
	[*] Number of Diff. Genes: 3
[*] working with: I_GranGl
	[*] Number of Diff. Genes: 14
[*] working with: I_DesmoNB
	[*] Number of Diff. Genes: 3
[*] working with: I_IsoNB
	[*] Number of Diff. Genes: 6
[*] working with: I_Ec2N
	[*] Number of Diff. Genes: 2
[*] working with: I_Ec1.5N
	[*] Number of Diff. Genes: 2
[*] working with: I_En1N
	[*] Number of Diff. Genes: 3
[*] working with: I_En3N
	[*] Number of Diff. Genes: 4
[*] working with: C_neuron
	[*] Number of Diff. Genes: 138
[*] working with: C_germline
	[*] Number of Diff. Genes: 84
[*] working with: C_nematoblast
	[*] Number of Diff. Genes: 124
[*] working with: C_nematocytes
	[*] Number of Diff. Genes: 191
[*] working with: C_gland_cell
	[*] Number of Diff. Genes: 22
[*] working with: C_progenitor
	[*] Number of Diff. Genes: 11
[*] working with: C_neuroprogenitor
	[*] Number of Diff. Genes: 21
[*] working with: C_EC_foot
	[*] Number of Diff. Genes: 54
[*] working with: C_EN_foot
	[*] Number of Diff. Genes: 25
[*] working with: C_tentacle
	[*] Number of Diff. Genes: 33
[*] working with: C_head
	[*] Number of Diff. Genes: 50
[*] working with: L_ENDODERM
	[*] Number of Diff. Genes: 1740
[*] working with: L_ECTODERM
	[*] Number of Diff. Genes: 2574
[*] working with: L_INTERSTITIAL
	[*] Number of Diff. Genes: 1611
[+] DONE

0

In [32]:
produce_tables_for_all_celtypes(wild, unique_celltypes, cleaned_merged_df, "wild")

[*] working on wild
[*] working with: Ec_Head
	[*] Number of Diff. Genes: 6
[*] working with: En_Head
	[*] Number of Diff. Genes: 4
[*] working with: Ec_BodyCol.SC
	[*] Number of Diff. Genes: 1
[*] working with: I_ISC
	[*] Number of Diff. Genes: 0
[*] working with: Ec_Peduncle
	[*] Number of Diff. Genes: 4
[*] working with: Ec_Tentacle
	[*] Number of Diff. Genes: 4
[*] working with: I_FemGC
	[*] Number of Diff. Genes: 18
[*] working with: Ec_BasalDisk
	[*] Number of Diff. Genes: 10
[*] working with: I_Neuro
	[*] Number of Diff. Genes: 0
[*] working with: I_EarlyNem
	[*] Number of Diff. Genes: 0
[*] working with: I_MaleGC
	[*] Number of Diff. Genes: 12
[*] working with: I_En2N
	[*] Number of Diff. Genes: 2
[*] working with: En_Foot
	[*] Number of Diff. Genes: 3
[*] working with: En_BodyCol.SC
	[*] Number of Diff. Genes: 0
[*] working with: I_ZymoGl
	[*] Number of Diff. Genes: 13
[*] working with: I_GlProgen
	[*] Number of Diff. Genes: 1
[*] working with: I_StenoNB
	[*] Number of Diff. Genes: 6
[*] working with: I_DesmoNC
	[*] Number of Diff. Genes: 8
[*] working with: I_IsoNC
	[*] Number of Diff. Genes: 6
[*] working with: I_StenoNC
	[*] Number of Diff. Genes: 7
[*] working with: En_Tentacle
	[*] Number of Diff. Genes: 4
[*] working with: I_Ec1N
	[*] Number of Diff. Genes: 2
[*] working with: I_Ec4N
	[*] Number of Diff. Genes: 2
[*] working with: I_SpumMucGl
	[*] Number of Diff. Genes: 7
[*] working with: I_Ec3N
	[*] Number of Diff. Genes: 3
[*] working with: I_GranGl
	[*] Number of Diff. Genes: 14
[*] working with: I_DesmoNB
	[*] Number of Diff. Genes: 3
[*] working with: I_IsoNB
	[*] Number of Diff. Genes: 6
[*] working with: I_Ec2N
	[*] Number of Diff. Genes: 2
[*] working with: I_Ec1.5N
	[*] Number of Diff. Genes: 2
[*] working with: I_En1N
	[*] Number of Diff. Genes: 3
[*] working with: I_En3N
	[*] Number of Diff. Genes: 4
[*] working with: C_neuron
	[*] Number of Diff. Genes: 138
[*] working with: C_germline
	[*] Number of Diff. Genes: 84
[*] working with: C_nematoblast
	[*] Number of Diff. Genes: 124
[*] working with: C_nematocytes
	[*] Number of Diff. Genes: 191
[*] working with: C_gland_cell
	[*] Number of Diff. Genes: 22
[*] working with: C_progenitor
	[*] Number of Diff. Genes: 11
[*] working with: C_neuroprogenitor
	[*] Number of Diff. Genes: 21
[*] working with: C_EC_foot
	[*] Number of Diff. Genes: 54
[*] working with: C_EN_foot
	[*] Number of Diff. Genes: 25
[*] working with: C_tentacle
	[*] Number of Diff. Genes: 33
[*] working with: C_head
	[*] Number of Diff. Genes: 50
[*] working with: L_ENDODERM
	[*] Number of Diff. Genes: 1740
[*] working with: L_ECTODERM
	[*] Number of Diff. Genes: 2574
[*] working with: L_INTERSTITIAL
	[*] Number of Diff. Genes: 1611
[+] DONE

0

In [33]:
produce_tables_for_all_celtypes(temp, unique_celltypes, cleaned_merged_df, "temp")

[*] working on temp
[*] working with: Ec_Head
	[*] Number of Diff. Genes: 6
[*] working with: En_Head
	[*] Number of Diff. Genes: 4
[*] working with: Ec_BodyCol.SC
	[*] Number of Diff. Genes: 1
[*] working with: I_ISC
	[*] Number of Diff. Genes: 0
[*] working with: Ec_Peduncle
	[*] Number of Diff. Genes: 4
[*] working with: Ec_Tentacle
	[*] Number of Diff. Genes: 4
[*] working with: I_FemGC
	[*] Number of Diff. Genes: 18
[*] working with: Ec_BasalDisk
	[*] Number of Diff. Genes: 10
[*] working with: I_Neuro
	[*] Number of Diff. Genes: 0
[*] working with: I_EarlyNem
	[*] Number of Diff. Genes: 0
[*] working with: I_MaleGC
	[*] Number of Diff. Genes: 12
[*] working with: I_En2N
	[*] Number of Diff. Genes: 2
[*] working with: En_Foot
	[*] Number of Diff. Genes: 3
[*] working with: En_BodyCol.SC
	[*] Number of Diff. Genes: 0
[*] working with: I_ZymoGl
	[*] Number of Diff. Genes: 13
[*] working with: I_GlProgen
	[*] Number of Diff. Genes: 1
[*] working with: I_StenoNB
	[*] Number of Diff. Genes: 6
[*] working with: I_DesmoNC
	[*] Number of Diff. Genes: 8
[*] working with: I_IsoNC
	[*] Number of Diff. Genes: 6
[*] working with: I_StenoNC
	[*] Number of Diff. Genes: 7
[*] working with: En_Tentacle
	[*] Number of Diff. Genes: 4
[*] working with: I_Ec1N
	[*] Number of Diff. Genes: 2
[*] working with: I_Ec4N
	[*] Number of Diff. Genes: 2
[*] working with: I_SpumMucGl
	[*] Number of Diff. Genes: 7
[*] working with: I_Ec3N
	[*] Number of Diff. Genes: 3
[*] working with: I_GranGl
	[*] Number of Diff. Genes: 14
[*] working with: I_DesmoNB
	[*] Number of Diff. Genes: 3
[*] working with: I_IsoNB
	[*] Number of Diff. Genes: 6
[*] working with: I_Ec2N
	[*] Number of Diff. Genes: 2
[*] working with: I_Ec1.5N
	[*] Number of Diff. Genes: 2
[*] working with: I_En1N
	[*] Number of Diff. Genes: 3
[*] working with: I_En3N
	[*] Number of Diff. Genes: 4
[*] working with: C_neuron
	[*] Number of Diff. Genes: 138
[*] working with: C_germline
	[*] Number of Diff. Genes: 84
[*] working with: C_nematoblast
	[*] Number of Diff. Genes: 124
[*] working with: C_nematocytes
	[*] Number of Diff. Genes: 191
[*] working with: C_gland_cell
	[*] Number of Diff. Genes: 22
[*] working with: C_progenitor
	[*] Number of Diff. Genes: 11
[*] working with: C_neuroprogenitor
	[*] Number of Diff. Genes: 21
[*] working with: C_EC_foot
	[*] Number of Diff. Genes: 54
[*] working with: C_EN_foot
	[*] Number of Diff. Genes: 25
[*] working with: C_tentacle
	[*] Number of Diff. Genes: 33
[*] working with: C_head
	[*] Number of Diff. Genes: 50
[*] working with: L_ENDODERM
	[*] Number of Diff. Genes: 1740
[*] working with: L_ECTODERM
	[*] Number of Diff. Genes: 2574
[*] working with: L_INTERSTITIAL
	[*] Number of Diff. Genes: 1611
[+] DONE

0

In [14]:
ecokd_male_germline = get_unique_genes_diffexpression_table(ecokd1, unique_celltypes, 'I_MaleGC')
wild_male_germline = get_unique_genes_diffexpression_table(wild, unique_celltypes, 'I_MaleGC')
temp_male_germline = get_unique_genes_diffexpression_table(temp, unique_celltypes, 'I_MaleGC')

ecokd_female_germline = get_unique_genes_diffexpression_table(ecokd1, unique_celltypes, 'I_FemGC')
wild_female_germline = get_unique_genes_diffexpression_table(wild, unique_celltypes, 'I_FemGC')
temp_female_germline = get_unique_genes_diffexpression_table(temp, unique_celltypes, 'I_FemGC')

In [15]:
ecokd_male_germline["ID"] = list(ecokd_male_germline.index)
ecokd_male_germline["ID"] = ecokd_male_germline.ID.apply(lambda x: x.split(".")[1])

ecokd1_merged_df = cleaned_merged_df.merge(ecokd_male_germline, on="ID")
ecokd1_merged_df[["ID","KO"]].to_csv("../results/gene_enrichment/ecokd1_malegermline.csv")

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,gene_id
HVAEP1.G000904,88.458618,1.505011,0.314000,4.793022,0.000002,0.000126,G000904
HVAEP15.G027692,1669.356109,-0.373037,0.100808,-3.700468,0.000215,0.009600,G027692
HVAEP14.G026547,105.860116,0.603757,0.221569,2.724921,0.006432,0.126527,G026547
HVAEP3.G005101,92.239247,0.983103,0.382292,2.571600,0.010123,0.169206,G005101
HVAEP14.G026375,62.227399,0.936059,0.435993,2.146959,0.031797,0.307648,G026375
HVAEP6.G011286,103.409800,0.857573,0.411841,2.082291,0.037316,0.333435,G011286
HVAEP2.G004254,13.724009,0.826301,0.415835,1.987087,0.046913,0.370663,G004254
HVAEP9.G016763,68.019184,0.851902,0.428777,1.986818,0.046943,0.370663,G016763
HVAEP13.G025545,337.277924,0.267882,0.136333,1.964905,0.049425,0.375672,G025545
HVAEP5.G010212,116.857125,0.766835,0.399103,1.921395,0.054682,0.391808,G010212
HVAEP2.G003773,104.505423,0.692531,0.402594,1.720170,0.085402,0.457359,G003773
HVAEP2.G003658,87.046410,0.700308,0.428559,1.634099,0.102238,0.490457,G003658
HVAEP3.G006353,209.364084,0.411192,0.270933,1.517692,0.129092,0.531232,G006353
HVAEP13.G024372,48.010767,0.516997,0.351167,1.472226,0.140960,0.546220,G024372
HVAEP9.G015935,278.064110,0.349783,0.256904,1.361531,0.173346,0.590322,G015935
HVAEP14.G026299,53.549049,0.493320,0.367728,1.341533,0.179747,0.596838,G026299
HVAEP2.G004487,121.682727,0.980419,0.740456,1.324074,0.185479,0.605016,G004487
HVAEP2.G004256,13.662087,0.698149,0.569467,1.225968,0.220211,0.636576,G004256
HVAEP6.G011209,125.939615,0.349336,0.294145,1.187632,0.234978,0.652214,G011209
HVAEP1.G001802,364.276244,0.680558,0.669515,1.016495,0.309394,0.718233,G001802
HVAEP1.G001201,319.023142,0.725501,0.750776,0.966335,0.333876,0.736313,G001201
HVAEP9.G016321,55.179962,0.303566,0.361296,0.840213,0.400789,0.776916,G016321
HVAEP14.G026282,91.633503,0.367734,0.439347,0.837000,0.402593,0.778530,G026282
HVAEP12.G022028,61.619381,0.350654,0.482963,0.726046,0.467810,0.817645,G022028
HVAEP12.G023896,449.692131,0.425159,1.129030,0.376570,0.706493,0.919129,G023896
HVAEP13.G025453,213.328141,0.235105,0.687055,0.342192,0.732206,0.930542,G025453
HVAEP10.G017764,144.771949,-0.034756,0.500568,-0.069434,0.944644,0.988186,G017764